name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: 'windows-latest'
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build
        run:  msbuild /m /p:Configuration=Release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: x64/Release/VersionShim.dll
          fail_on_unmatched_files: true
